### ISSUE TITLE
Does CsoundQt use Csound’s API for syntax checking?

### ISSUE THREAD

**Issue by nwhetsell** [mantaraya36/CsoundQt#191]
Based on a reply to https://github.com/csound/csound/issues/540#issuecomment-150273544, there seems to be a chance that CsoundQt uses Csound’s API to perform live syntax checking, which is what I’m trying to do [here](https://github.com/csound/csound/issues/540#issue-112833872). I haven’t been able to find this in CsoundQt’s source code, though. [`DocumentView::syntaxCheck()`](https://github.com/mantaraya36/CsoundQt/blob/master/src/documentview.cpp#L646) seems like a possibility, but that doesn’t look like it’s making any Csound API calls. Also, typing some invalid code into CsoundQt doesn’t seem to perform syntax checking as far as I can see. Does CsoundQt use Csound’s API for syntax checking and, if so, can you point me toward the code that does this?

**Comment by mantaraya36** [comment]
Hi,

No, there is not a lot you can currently get about opcodes from the csound
API AFAIK. I am using the opcodes.xml generated by scripts in the manual to
do this.

I think it might be a good idea to add some API to query available opcodes
and this could tie into Steven's idea of having an opcode API.

It would be a good idea to ask this on the main csound list.

Cheers,
Andrés
