### ISSUE TITLE
csound7  branch: widgets with chnset not working

### ISSUE THREAD

**Issue by joachimheintz** [mantaraya36/CsoundQt#411]
it seems that in the csound7 branch widgets do not work at all with chnset.
please try for instance the built-in Examples > CsoundQt > Widgets > ControllerWidget
or https://github.com/csudo/csudo/blob/master/csqt/CsQtMeter.csd
also chnget is not working as i see now:
```
chn_k "test",1
instr Test
  printk(.1,chnget("test"))
endin
schedule("Test",0,100)
```

invalue/outvalue are working.

**Comment by tarmoj** [comment]
Hi!

Hm, I have no problem with CsoundQt 1.1.3+Csound 7 AppImage with the
ControllerWidget example. Also the code nelow works for me as expected. I
have not done a recent build, maybe something has changed in Csound code.
If will try later to rebuild both Csound and CsoundQt to test.

This works fine for me (with a slider widget):

;;channels

chn_k "value",3


alwayson 1

instr 1

printk2 chnget:k("value")

if metro(1)==1 then

chnset random:k(0, 1), "value"

endif

endin


tarmo




Kontakt joachimheintz ***@***.***>) kirjutas kuupäeval P,
20. oktoober 2024 kell 17:54:

**Comment by joachimheintz** [comment]
thank you --- i did a rebuild and it works now.  i think my csound7 code was not up to date; i don't think it was about csound.
